### ISSUE TITLE
Make non-PBC GO sheet

### ISSUE THREAD

**Issue by maalbadri** [velocirobbie/make-graphitics#1]
Hi Robbie,

I’ve just come across this repository and would love to use it as a starting point for some of my work. 

How easy is it to implement the GO sheet without PBC?

**Comment by velocirobbie** [comment]
(moving the discussion here from email for convenience)

From what's been said, to create what you want all that's needed is a rectangular graphene flake class. This would function like any other molecule. I am going to take a look at this over the next couple of weeks when I have some time, I don't think it should be too difficult to add, but i'll let you know

**Comment by velocirobbie** [comment]
So i'm planning to make a class that builds a rectangular sheet with hydrogen terminated edges that takes x,y length as inputs. It should behave similarly to the hexagon class otherwise, does that work for your needs?

**Comment by velocirobbie** [comment]
I've added a rectangle flake builder. Should be able to use the `make_GO_rect.py` or `make_grpahene_rect.py` for your needs. Let me know if these work/are useful then I'll close this issue

**Comment by maalbadri** [comment]
Sorry only just saw these comments - I'll change my notification settings.

That's perfect, really appreciate it. I'll test this tomorrow and will be in touch!

**Comment by maalbadri** [comment]
OK it looks like it works fine  😃 -- just one thing that I noticed previously, you're using the Nitrogen label in the xyz file to illustrate islands I assume? I recommend you highlight this on the README in case the xyz is used to perform subsequent calculations.
