### ISSUE TITLE
Bug in make_GO_stack

### ISSUE THREAD

**Issue by mcy01** [velocirobbie/make-graphitics#2]
@velocirobbie 
An attribute-error: **_"Combine" object has no attribute  "bond_types"_** appeared when running make_GO_stack. It locates at line 32 in params.py as followed:

`...
OH/epoxy =  1.2

Traceback (most recent call last):
  File "D:##/Python/make_GO_stack.py", line 24, in <module>
     Parameterise(sim, new_layer.vdw_defs)
  File "D:##\Python\scripts\params.py", line 32, in __init__
     crystal.bond_coeffs = self.match_bonds(crystal.bond_types)

**AttributeError: 'Combine' object has no attribute 'bond_types'**

Atom label -> OPLS vdw definitions: 	{1: 90, 2: 91, 3: 101, 4: 96, 5: 97, 6: 122, 7: 109, 8: 209, 9: 210, 10: 211, 11: 108}
Atom label -> OPLS type definitions: 	{1: 48, 2: 49, 3: 13, 4: 5, 5: 7, 6: 20, 7: 5, 8: 3, 9: 4, 10: 5, 11: 48}

Process finished with exit code 1`

**Comment by velocirobbie** [comment]
Hi, I think I've fixed this error now, the 'combine' procedure had been broken in a recent update. Could you try it again, if it works I can close the issue

**Comment by mcy01** [comment]
It works! Thank you very much.

**Comment by velocirobbie** [comment]
Happy to help, let me know if you have any other queries
